version: '3'

services:
    workspace:
        restart: always
        image: framgia/laravel-workspace
        volumes:
            - ./:/var/www/laravel
        tty: true
    php-fpm:
        restart: always
        image: framgia/laravel-php-fpm
        volumes:
            - ./:/var/www/laravel
        expose:
            - "9000"
    nginx:
        restart: always
        image: framgia/laravel-nginx
        volumes:
            - ./:/var/www/laravel
            - ./docker/dev/logs/nginx:/var/log/nginx
        ports:
            - "8082:80"
    mysql:
        restart: always
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./docker/dev/provision/mysql/init:/docker-entrypoint-initdb.d
        volumes:
            - ./docker/dev/data/mysql:/var/lib/mysql
        expose:
            - "3306"
        ports:
            - "8083:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    mail-server:
        restart: always
        image: mailhog/mailhog
        user: root # Needed if using maildir
        environment:
            MH_STORAGE: maildir
            MH_MAILDIR_PATH: /var/data/mailhog
        volumes:
            - ./docker/dev/data/mailhog:/var/data/mailhog
        expose:
            - "1025" # SMTP Server to send mail
            - "8025" # HTTP Server to check mail
        ports:
            - "8084:8025"
    adminer:
        restart: always
        image: adminer
        expose:
            - "8080"
        ports:
            - "8085:8080"
        environment:
            ADMINER_DEFAULT_SERVER: mysql
            ADMINER_DESIGN: "pappu687"
    # redis:
    #     restart: always
    #     image: redis
    #     expose:
    #         - "6379"
    #     volumes_from:
    #         - data
